# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa8989ee71fa6a82e04b017d68411cb2f09712a157dd120e067302effe27426ac93143601cab5c09aff03cfe63d2898567c19a155b2c87c54a2e2988eca212f

test:
  secret_key_base: bf01cc994962397a1bf3e7f48af48dc53b839d7c7b25d88ca5505c187717692c2a0d8b1359bd5945a027e2054273424b15bee993f2bfc4407fc9af0da2d4dc02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
